version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: dasu-frontend
    restart: unless-stopped
    ports:
      - 80:80
    networks:
      - dasu-network

  api:
    build: ./api
    container_name: dasu-api
    restart: unless-stopped
    networks:
      - dasu-network
    depends_on:
      - api_db

  api_db:
    image: library/mysql:8.0.22
    container_name: dasu-db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=api_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
    volumes:
      - mysql_db:/var/lib/mysql
    networks:
      - dasu-network

volumes:
  mysql_db:

networks:
  dasu-network:
    driver: bridge
