version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: dasu-frontend
    restart: unless-stopped
    ports:
      - 49153:49153
    volumes:
      - ./frontend/src:/usr/src/app/src
    command: ng serve --port 4200 --host 0.0.0.0 --disableHostCheck
    networks:
      - dasu-network

  api:
    build: ./api
    container_name: dasu-api
    restart: unless-stopped
    networks:
      - dasu-network
    depends_on:
      - api_db

  api_db:
    image: library/mysql:8.0.22
    container_name: dasu-db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=api_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
    volumes:
      - mysql_db:/var/lib/mysql
    networks:
      - dasu-network

  nginx:
    image: library/nginx:1.19.3-alpine
    container_name: dasu-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./frontend/nginx.conf.dev:/etc/nginx/conf.d/default.conf
    command: ["nginx", "-g", "daemon off;"]
    depends_on:
      - frontend
      - api
    networks:
      - dasu-network

volumes:
  mysql_db:

networks:
  dasu-network:
    driver: bridge
